config/routes.rb
Taskmanager::Application.routes.draw do
  devise_for :users

devise_scope :user do

    get "login", to: "devise/sessions#new", as: :login
    get "logout", to: "devise/sessions#destroy", as: :logout
    get "register", to: "devise/registrations#new", as: :register
  end

  resources :tasks

get "Tareas", to: "tasks#index", as: :Tareas

  root :to => 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :status, :user_id
  validates :name, presence: true, length: {
                                minimum: 6
                          },
                        uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :lastname, :name, :username


  validates :name, presence: true
  validates :lastname, presence: true
  validates :email, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!, only: [:new]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tasks }
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @task = Task.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "TaskManager" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<nav class="top-bar" data-topbar>
    <ul class="title-area">
      <li class="name">
        <h1><a href="/tasks#index">Taskmanager</a></h1>
      </li>
      <li class="toggle-topbar menu-icon">
        <a href="#">Menu</a>
      </li>
    </ul>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">

       <% if user_signed_in? %>

        <li>
          <%=
          link_to current_user.name, edit_user_registration_path
          %>
        </li>
        <li>
          <%=
          link_to 'Log Out', logout_path, method: :get
          %>
        </li>

        <% else %>

        <li>
           <%=
          link_to 'Sign Up', register_path, class: "button"
          %>
        </li>
        <li>
          <%=
          link_to 'Sign In', login_path
          %>
        </li>

        <% end %>
      </ul>
    </section>
  </nav>
  <div class="row">
    <div class="large-12 columns">
      <% if flash[:notice] %>
      <div data-alert class="alert-box radius">
      <%= notice %>
      <a href="#" class="close">&times;</a>
      </div>
      <% end %>

      <% if flash[:alert] %>
      <div data-alert class="alert-box radius warning">
      <%= alert %>
      <a href="#" class="close">&times;</a>
      </div>
      <% end %>

      <%= yield %>
    </div>
  </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <% if user_signed_in? %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "button" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tareas</h1>

<%= link_to 'New Task', new_task_path, class: "button" %>

<% @tasks.each do |task| %>
  <div class="panel">

    <p><%= task.name %></p>
    <p>
      <strong><%= task.user.name + " " + task.user.lastname %></strong>,

    </p>
    <p><%= if task.status == "1"
        "Terminado"
        else
          "No Terminado"
        end %>
    </p>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @task.name %>
</p>

<p>
  <b>User:</b>
  <%= @task.user.name  + " " + @task.user.lastname %>
</p>

<p>
  <b>Status:</b>
  <%= if @task.status == "1"
      "Terminado"
      else
        "No Terminado"
      end %>

</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>